config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/users'

  root to: "posts#index"

  resources :posts do

    resources :likes, module: "posts", only: [:create, :destroy]

    resources :comments do

      resources :likes, module: "comments", only: [:create, :destroy]

    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  resources :likes, only: [:destroy]
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable
  has_many :likers, through: :likes, source: :user
  has_many :notifications, as: :notifiable

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :content, presence: true

end

app/controllers/comments/likes_controller.rb
class Comments::LikesController < LikesController
 before_filter :set_likeable

 def get_likers
    user_array = []
    @likeable.likers.each {|user| user_array << user }
    user_array << @likeable.user
    user_array = user_array.uniq - [current_user]
    user_array
  end

  def create_notifications
    user_array = get_likers
    user_array.each do |user|
      Notification.create(recipient: user, actor: current_user, action: "liked a comment by #{@likeable.user.name}", url: post_path(@likeable.post), notifiable: @like)
    end
  end

  private
    def set_likeable
      array = request.path.split("/")
      resource, id = array[3], array[4]
      @likeable = resource.singularize.classify.constantize.find(id)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "Comment posted!"
      # Create notifications
      notifiable_users = get_notifiable_users
      notifiable_users.each do |noti_user|
        Notification.create(recipient: noti_user, actor: current_user, action: "commented on #{@post.user.name}'s post.", notifiable: @comment, url: post_path(@post))
      end
      redirect_to :back
    else
      flash.now[:danger] = "Error posting comment."
      render post_path(@post)
    end
  end


  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def get_notifiable_users
      notifiable_users = []
      @post.commenters.each { |x| notifiable_users << x }
      @post.likers.each { |x| notifiable_users << x }
      notifiable_users << @post.user
      notifiable_users = notifiable_users.uniq
      notifiable_users -= [current_user]
      notifiable_users
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

end

app/views/comments/_comment.html.erb
 <div class="comment clearfix">
    <%= link_to gravatar_for(comment.user, options = { size: 30 }), user_path(comment.user), class: "float-left" %>
    <p><strong><% if current_user == comment.user %><%= link_to "You", user_path(comment.user) %><% else %><%= link_to comment.user.name, user_path(comment.user) %><% end %></strong> said: <%= comment.content %> (<%= distance_of_time_in_words_to_now(comment.created_at) %></em> ago)
    <%= render partial: "likes/heart_like", locals: { post: post, likeable: comment} %></p>
  </div>

app/views/comments/_new.html.erb
<table class="comment-form">
  <tr>
    <td class="comment-field">
  <%= form_for(post.comments.build, url: post_comments_path(post.id), method: "post") do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
  <%= f.text_area :content, placeholder: "Have a comment?", class: "comment-text" %></td>
    <td><%= f.submit "Comment", class: "button" %></td>
  </tr>
</table>
<% end %>

app/views/comments/new.html.erb
<%= form_for(post.comments.build, url: post_comments_path(post.id), method: "post") do |f| %>
  <%= hidden_field_tag :post_id, post.id %>
  <%= f.text_area :content, placeholder: "Have a comment?" %>
  <%= f.submit "Comment" %>
<% end %>