config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/users'

  root to: "posts#index"

  resources :posts do

    resources :likes, module: "posts", only: [:create, :destroy]

    resources :comments do

      resources :likes, module: "comments", only: [:create, :destroy]

    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  resources :likes, only: [:destroy]
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :likeable, polymorphic: true
  has_many :notifications, as: :notifiable
  validates :user, presence: true
  validates :likeable, presence: true
end

app/controllers/comments/likes_controller.rb
class Comments::LikesController < LikesController
 before_filter :set_likeable

 def get_likers
    user_array = []
    @likeable.likers.each {|user| user_array << user }
    user_array << @likeable.user
    user_array = user_array.uniq - [current_user]
    user_array
  end

  def create_notifications
    user_array = get_likers
    user_array.each do |user|
      Notification.create(recipient: user, actor: current_user, action: "liked a comment by #{@likeable.user.name}", url: post_path(@likeable.post), notifiable: @like)
    end
  end

  private
    def set_likeable
      array = request.path.split("/")
      resource, id = array[3], array[4]
      @likeable = resource.singularize.classify.constantize.find(id)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  # Like a model
  def create
    @user = current_user
    @like = @user.likes.build(likeable: @likeable)
    @like.save
    create_notifications
    redirect_to :back
  end

  # Dislike a model
  def destroy
    @user = current_user
    @like = @user.likes.find(params[:id])
    @like.destroy
    redirect_to :back
  end



end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < LikesController
 before_filter :find_likeable

  def get_likers
    user_array = []
    @likeable.likers.each {|user| user_array << user }
    @likeable.commenters.each {|user| user_array << user }
    user_array << @likeable.user
    user_array = user_array.uniq - [current_user]
    user_array
  end

  def create_notifications
    user_array = get_likers
    user_array.each do |noti_user|
      Notification.create(recipient: noti_user, actor: current_user, action: "liked a post by #{@likeable.user.name}", url: post_path(@likeable), notifiable: @like)
    end
  end

  private
    def find_likeable
      resource, id = request.path.split("/")[1,2]
      @likeable = resource.singularize.classify.constantize.find(id)
    end

end

app/helpers/likes_helper.rb
module LikesHelper

end

app/views/likes/_button_like.html.erb
<% if current_user.likes?(likeable) %>
  <%= button_to(current_user.likes.find_by(likeable_id: likeable.id), method: :delete, class: "alert hollow button float-right", id: "like-#{likeable.id}") do %>
    <i class="fi-heart"></i> Liked this (<%=  likeable.likes.count %>)
  <% end %>
<% else %>
  <%= button_to polymorphic_path([likeable, Like], method: :post), class: "secondary hollow button float-right", id: "like-#{likeable.id}" do %>
    <i class="fi-heart"></i> Like (<%=  likeable.likes.count %>)
  <% end %>
<% end %>

app/views/likes/_heart_like.html.erb
<% if current_user.likes?(likeable) %>
  <%= link_to(current_user.likes.find_by(likeable_id: likeable.id), method: :delete, class: "liked") do %>
    <i class="fi-heart"></i> (Liked by <%=  likeable.likes.count %> users: <% likeable.likers.each_with_index do |liker, i| %>
      <% if likeable.likers.length == 1 %>
        <%= link_to liker.name, user_path(liker) %>
      <% elsif i+1 == likeable.likers.length %>
        and <%= link_to liker.name, user_path(liker) %>
      <% else %>
        <%= link_to liker.name, user_path(liker) %>,
      <% end %>
    <% end %>)
  <% end %>
<% else %>
  <%= link_to post_comment_likes_path(post, comment_id: likeable.id), method: :post do %>
    <i class="fi-heart"></i> (<%=  likeable.likes.count %>)
  <% end %>
<% end %>

app/views/likes/_post_likes.html.erb
  <% if current_user.likes?(post) %>
    <p><i class="fi-heart liked"></i> Liked by <%= post.likes.count %> users:
      <% post.likers.each_with_index do |liker, i| %>
        <% if post.likers.length == 1 %>
          <%= link_to liker.name, user_path(liker) %>
        <% elsif i+1 == post.likers.length %>
          and <%= link_to liker.name, user_path(liker) %>
        <% else %>
          <%= link_to liker.name, user_path(liker) %>,
        <% end %>
      <% end %>
    <% end %>