config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/users'

  root to: "posts#index"

  resources :posts do

    resources :likes, module: "posts", only: [:create, :destroy]

    resources :comments do

      resources :likes, module: "comments", only: [:create, :destroy]

    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  resources :likes, only: [:destroy]
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
   include Amistad::FriendModel
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, allow_nil: true, allow_blank: false,
            length: { maximum: 50 }

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :likeable, source_type: "Post"
  has_many :liked_comments, through: :likes, source: :likeable, source_type: "Comment"
  has_many :notifications, foreign_key: :recipient_id
  has_many :notifications, as: :notifiable
  has_many :photos, through: :posts
  after_create :welcome

  has_attached_file :avatar, styles: { medium: "400x400>", thumb: "120x120>", tiny: "40x40>" },  :url  => "/assets/users/:id/:style/:basename.:extension",
      :path => ":rails_root/public/assets/users/:id/:style/:basename.:extension"
 validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/gif', 'image/png']


  def welcome
    welcome_email
  end

  def feed
    friend_ids = []
    self.friends.each { |f| friend_ids << f.id }
    Post.where("user_id IN (?) or user_id = ?", friend_ids, id).order("created_at DESC")
  end

  def likes?(likeable)
    if likeable.class == Post
      self.liked_posts.include?(likeable)
    elsif likeable.class == Comment
      self.liked_comments.include?(likeable)
    end
  end

  private

    def welcome_email
      NoticeMailer.welcome(self).deliver_now!
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def index
    @users = User.paginate(:page => params[:page], :per_page => 16).order(
      'name ASC')
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts.paginate(:page => params[:page], :per_page => 16).order('created_at DESC')
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "User info saved."
      redirect_to @user
    else
      flash.now[:alert] = "User info not updated."
      render :edit
    end
  end


  private

    def user_params
      params.require(:user).permit(:name, :from, :gender, :avatar)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/users/_profile_photo.html.erb
<div class="photo-container">
  <% if @user.avatar_file_name.nil? %>
    <%= gravatar_for @user, options = { size: 400 }%>
  <% else %>
    <%= image_tag @user.avatar.url %>
  <% end %>
</div>

app/views/users/_profile_photo_tiny.html.erb
<% if post.user.avatar_file_name.nil? %>
  <%= link_to gravatar_for(post.user, options = { size: 40 }), user_path(post.user), class: "float-left" %>
<% else %>
  <%= link_to( image_tag(post.user.avatar.url(:tiny)), user_path(post.user), class: "float-left gravatar") %>
<% end %>

app/views/users/_user.html.erb
<div class="column user-grid">
  <%= link_to gravatar_for(user, options = { size: 120 }), user_path(user) %> 
    <%= link_to user.name, user_path(user) %><br>
    <!-- relationshhip --> 
    <% if current_user.friend_with?(user) %>
      <p><i class="fi-torsos"></i> Friend</p>
    <% elsif current_user.invited?(user) %>
      <p>Pending request...</p>
    <% elsif user.invited?(current_user) %>
      <%= link_to('<i class="fi-check"></i> Accept'.html_safe, friend_path(user), method: :put, class: 'success button') %>
      <%= link_to('<i class="fi-x"></i> Accept'.html_safe, friend_path(user), method: :delete, class: 'alert button') %>
    <% elsif current_user == user %>
      <p>Your profile</p>
    <% else %>
      <%= link_to('<i class="fi-torsos"></i> Add Friend'.html_safe, friends_path(user_id: user.id), method: :post, class: "button") %>
    <% end %>
</div>

app/views/users/edit.html.erb
<h1>Update Info</h1>
<p>Update the information that appears on your profile.</p>

<%= form_for @user, url: {action: 'update'}, html: { method: "patch", multipart: true } do |f| %>
  <%= f.label "Name (required)", class: "strong-label"%>
  <%= f.text_field :name %>
  <%= f.label :from, class: "strong-label" %>
  <%= f.text_field :from %>
  <%= f.label :gender, class: "strong-label" %>
  <%= f.text_field :gender %>
  <%= f.label "Profile Photo", class: "strong-label" %>
  <p><strong>Please note:</strong> Your profile photo will be the default Gravatar icon (see preview below), unless you set up a profile photo of your own. You can upload a file (left) or change your Gravatar on the right.</p>
  <div class="row">
    <div class="small-6 columns">
      <em>Upload a photo:</em>
      <%= f.file_field :avatar %>
    </div>
    <div class="small-6 columns">
      <em>Current Gravatar</em>
      <a href="http://gravatar.com/emails" target="_blank" >(Change)</a>  <%= gravatar_for @user %>
    </div>
  </div>
  <br>
  <%= f.submit "Update Info", class: "expanded button" %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate @users, renderer: FoundationPagination::Rails %>

<div class="row small-up-2 medium-up-2 large-up-4" id="user-grid">
<% for user in @users %>
  <div class="column user-block">
    <h5><%= link_to user.name, user_path(user) %></h5>
      <% if user.avatar_file_name.nil? %>
        <%= link_to gravatar_for(user, options = { size: 120 }), user_path(user) %>
      <% else %>
        <%= link_to( image_tag(user.avatar.url(:thumb)), user_path(user)) %>
      <% end %>
    <!-- relationshhip -->
    <% if current_user == user %>
      <p>Your profile</p>
    <% elsif current_user.friend_with? user %>
      <p>Already friends</p>
    <% elsif current_user.invited? user %>
      <p>Pending request...</p>
    <% elsif user.invited? current_user %>
      <p><%= link_to '<i class="fi-check"></i> Confirm friend'.html_safe, friend_path(user), method: :put %></p>
    <% else %>
      <p><%= link_to('<i class="fi-torsos"></i> Add Friend'.html_safe,  friends_path(user_id: user), method: :post) %></p>
    <% end %>
  </div>

<% end %>
</div>

<%= will_paginate @users, renderer: FoundationPagination::Rails %>

app/views/users/show.html.erb
<div class="row">
  <div class="small-12 columns clearfix profile-header">

    <h1 class="username"><%= @user.name %></h1>
  </div>
</div>
<div class="row">
  <div class="small-12 medium-4 large-4 columns callout">

    <%= render "users/profile_photo" %>

    <h2>About</h2>
    <p>From: <%= @user.from %></p>
    <p>Gender: <%= @user.gender %></p>
    <br>
    <h4>Likes</h4>
    <p>Likes <%= @user.liked_posts.count %> posts</p>
    <p>Likes <%= @user.liked_comments.count %> comments</p>

    <% if current_user == @user %>
      <%= link_to "Update my info", edit_user_path(@user) %>
    <% elsif @user.invited_by? current_user %>
      <p>Pending friend request...</p>
    <% elsif @user.friend_with? current_user %>
      <p>Already friends</p>
    <% end %>
  </div>

  <div class="small-12 medium-8 large-8 columns">
    <% if current_user == @user || current_user.friend_with?(@user) %>

      <% if current_user == @user %>
        <%= render partial: "posts/post_form" %>
      <% end %>

      <%= render @posts %>

      <%= will_paginate @posts, renderer: FoundationPagination::Rails %>
    <% else %>
      <%= link_to('<i class="fi-torsos"></i> Add Friend'.html_safe,  friends_path(user_id: @user), class: "button expanded", method: :post) %>
    <% end %>
  </div>
</div>