config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '/users'

  root to: "posts#index"

  resources :posts do

    resources :likes, module: "posts", only: [:create, :destroy]

    resources :comments do

      resources :likes, module: "comments", only: [:create, :destroy]

    end
  end
  resources :users, only: [:index, :show, :edit, :update]
  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  resources :likes, only: [:destroy]
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
end

app/views/layouts/_flash.html.erb
<div class="small-10 small-offset-1">
  <% flash.each do |message_type, message| %>
    <div class="<%= message_type %> callout"><%= message %></div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li><%= link_to "OdinFB", root_url %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Directory", users_path %></li>
        <li>
          <a href="#"><%= current_user.name %></a>
          <ul class="menu vertical">
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <li><%= link_to "Friends", friends_path %></li>
            <hr>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
            <li><%= link_to "Edit Account", edit_user_registration_path %></edit>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <% if user_signed_in? %>
      <li data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
          <a data-behavior="notifications-link">
            <i class="fi-flag"></i><span class="badge" data-behavior="unread-count"></span></a>
        <ul class="menu vertical" data-behavior="notification-items">
        </ul>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Odin-Facebook" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <div class="row">

      <%= render "layouts/flash" %>

      <%= yield %>
    </div>


    <script>
      $(document).foundation();
    </script>
  </body>
</html>